# Boolean Indexing:

In [1]:
import numpy as np

In [2]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [3]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [4]:
data

array([[-0.06336328, -0.92126552, -0.22426104,  0.10734953],
       [ 0.61825707, -0.12814143, -1.04794923, -0.40015471],
       [ 1.25805946,  0.14361262, -0.73010754, -0.39229884],
       [ 1.12348075,  0.18012639,  1.49227709,  0.44715011],
       [-0.53131931, -0.08321951, -1.40306987, -0.63336095],
       [ 0.03780878, -1.0351638 , -0.99955148, -1.04399537],
       [-0.1653008 ,  0.19929627, -0.92399814,  0.53731362]])

In [5]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [6]:
data[names == 'Bob']

array([[-0.06336328, -0.92126552, -0.22426104,  0.10734953],
       [ 1.12348075,  0.18012639,  1.49227709,  0.44715011]])

In [7]:
data[names == 'Bob', 2:]

array([[-0.22426104,  0.10734953],
       [ 1.49227709,  0.44715011]])

In [8]:
data[names == 'Bob', 3]

array([0.10734953, 0.44715011])

In [9]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [10]:
data[names != 'Bob']

array([[ 0.61825707, -0.12814143, -1.04794923, -0.40015471],
       [ 1.25805946,  0.14361262, -0.73010754, -0.39229884],
       [-0.53131931, -0.08321951, -1.40306987, -0.63336095],
       [ 0.03780878, -1.0351638 , -0.99955148, -1.04399537],
       [-0.1653008 ,  0.19929627, -0.92399814,  0.53731362]])

In [11]:
data[~(names != 'Bob')]

array([[-0.06336328, -0.92126552, -0.22426104,  0.10734953],
       [ 1.12348075,  0.18012639,  1.49227709,  0.44715011]])

In [12]:
~(names != 'Bob')

array([ True, False, False,  True, False, False, False])

In [13]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [14]:
data[mask]

array([[-0.06336328, -0.92126552, -0.22426104,  0.10734953],
       [ 1.25805946,  0.14361262, -0.73010754, -0.39229884],
       [ 1.12348075,  0.18012639,  1.49227709,  0.44715011],
       [-0.53131931, -0.08321951, -1.40306987, -0.63336095]])

In [15]:
data[data<0] = 0

In [16]:
data

array([[0.        , 0.        , 0.        , 0.10734953],
       [0.61825707, 0.        , 0.        , 0.        ],
       [1.25805946, 0.14361262, 0.        , 0.        ],
       [1.12348075, 0.18012639, 1.49227709, 0.44715011],
       [0.        , 0.        , 0.        , 0.        ],
       [0.03780878, 0.        , 0.        , 0.        ],
       [0.        , 0.19929627, 0.        , 0.53731362]])

In [17]:
data[names != 'Joe'] = 7

In [18]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.61825707, 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.03780878, 0.        , 0.        , 0.        ],
       [0.        , 0.19929627, 0.        , 0.53731362]])

In [19]:
names != 'Joe'

array([ True, False,  True,  True,  True, False, False])