# Data Types for ndarrays

In [1]:
import numpy as np

In [4]:
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr1

array([1., 2., 3.])

In [5]:
arr1.dtype

dtype('float64')

In [6]:
arr2 = np.array([1., 2., 3., 4., 5.])
arr2

array([1., 2., 3., 4., 5.])

In [7]:
arr2.astype(np.int32)

array([1, 2, 3, 4, 5])

In [8]:
numeric_string = np.array(['1', '2', '3'])
numeric_string

array(['1', '2', '3'], dtype='<U1')

In [9]:
numeric_string.astype(float)

array([1., 2., 3.])