# Writing new Universal Functions:

In [1]:
import numpy as np

In [2]:
def add_elements(x, y):
    return x + y

In [3]:
add = np.frompyfunc(add_elements, 2, 1)

In [4]:
add(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [5]:
add2 = np.vectorize(add_elements, otypes = [np.float64])

In [8]:
add2(np.arange(10), np.arange(10))

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [9]:
arr = np.arange(10) * 100
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [10]:
i = [7, 1, 2, 6]

In [11]:
arr[i]

array([700, 100, 200, 600])

In [12]:
arr.take(i)

array([700, 100, 200, 600])

In [13]:
arr.put(i, 42)

In [14]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [17]:
arr.put(i, [3, 65, 12, 56])

In [18]:
arr

array([  0,  65,  12, 300, 400, 500,  56,   3, 800, 900])

In [23]:
j = [2, 0, 2, 1]

In [24]:
arr2 = np.random.randn(2, 4)

In [25]:
arr2

array([[ 1.35753475,  0.67919255,  1.45182595,  0.89473862],
       [-0.70519067,  0.03077377, -0.99928051,  0.46475359]])

In [26]:
arr2.take(j, axis = 1)

array([[ 1.45182595,  1.35753475,  1.45182595,  0.67919255],
       [-0.99928051, -0.70519067, -0.99928051,  0.03077377]])

In [27]:
arr3 = np.random.randn(5, 5)
arr3

array([[-0.87452361,  0.65193585,  0.84442632,  0.85242367,  0.423762  ],
       [ 0.60439515, -1.67308626, -0.89865639, -0.50211924, -0.60817335],
       [ 1.35858166, -0.41221534, -0.43290767,  0.59280763,  0.08478559],
       [-0.05809007, -0.83702528,  0.40099445, -0.00420952, -0.96913231],
       [-2.3018928 , -1.04268214, -1.64466196,  0.26205831, -1.2199595 ]])

In [29]:
arr3[::2].sort()

In [30]:
arr3

array([[-0.87452361,  0.423762  ,  0.65193585,  0.84442632,  0.85242367],
       [ 0.60439515, -1.67308626, -0.89865639, -0.50211924, -0.60817335],
       [-0.43290767, -0.41221534,  0.08478559,  0.59280763,  1.35858166],
       [-0.05809007, -0.83702528,  0.40099445, -0.00420952, -0.96913231],
       [-2.3018928 , -1.64466196, -1.2199595 , -1.04268214,  0.26205831]])

In [31]:
arr3[::2]

array([[-0.87452361,  0.423762  ,  0.65193585,  0.84442632,  0.85242367],
       [-0.43290767, -0.41221534,  0.08478559,  0.59280763,  1.35858166],
       [-2.3018928 , -1.64466196, -1.2199595 , -1.04268214,  0.26205831]])

In [33]:
a = np.array([1, 3, 2, 5, 4])
a

array([1, 3, 2, 5, 4])

In [34]:
a[::-1]

array([4, 5, 2, 3, 1])