# Universal Functions:

In [8]:
import numpy as np

In [9]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [11]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [14]:
x = np.random.randn(10)
x

array([-0.43555856,  0.01617981, -0.09765732,  2.12253742, -1.41041189,
        0.24291159,  0.54364091, -1.14814726, -1.04501303, -0.44938981])

In [15]:
arr2 = np.arange(10, 20)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.maximum(arr, arr2)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
a = np.array([2, 7, 12, 3, 3452])
b = np.array([20, 354, 67, 4303, 3231])

In [18]:
print(a, b)

[   2    7   12  903 3452] [  20  354   67 4303 3231]


In [19]:
np.maximum(a, b)

array([  20,  354,   67, 4303, 3452])

In [20]:
remainder, whole_part = np.modf(x)

In [21]:
remainder

array([-0.43555856,  0.01617981, -0.09765732,  0.12253742, -0.41041189,
        0.24291159,  0.54364091, -0.14814726, -0.04501303, -0.44938981])

In [22]:
whole_part

array([-0.,  0., -0.,  2., -1.,  0.,  0., -1., -1., -0.])

In [25]:
np.in1d(a, [1, 2, 3])

array([ True, False, False,  True, False])

In [26]:
np.unique(b)

array([  20,   67,  354, 3231, 4303])

In [27]:
x = np.array([1,2,1,3,2,3,5,5,4])
x

array([1, 2, 1, 3, 2, 3, 5, 5, 4])

In [28]:
np.unique(x)

array([1, 2, 3, 4, 5])