# Fancy Indexing:

In [1]:
import numpy as np

In [2]:
arr = np.empty((8,4))
arr

array([[       nan, 9.881e-324, 4.842e-321, 4.941e-324],
       [6.146e-321, 1.976e-323, 5.079e-321, 2.031e-321],
       [5.138e-321, 2.031e-321, 5.198e-321, 2.031e-321],
       [3.656e-321, 2.031e-321, 6.146e-321, 2.031e-321],
       [6.146e-321, 1.976e-323, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000]])

In [3]:
for i in range(8):
    arr[i] = i

In [4]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [5]:
arr[[4, 5, 0, 2]]

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [0., 0., 0., 0.],
       [2., 2., 2., 2.]])

In [6]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [8]:
arr2 = np.arange(32).reshape((8, 4))
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [9]:
arr2[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [13]:
arr2[[1, 5, 7, 2]][0:3, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30]])

In [11]:
arr2[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])