# Some more useful functions:

In [1]:
import numpy as np

In [6]:
arr = np.arange(15).reshape(-1, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [15]:
display(arr1, arr2)

array([[1, 2, 3],
       [4, 5, 6]])

array([[ 7,  8,  9],
       [10, 11, 12]])

In [19]:
np.concatenate([arr1, arr2], axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [20]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [32]:
display(arr1, arr2)

array([[1, 2, 3],
       [4, 5, 6]])

array([[ 7,  8,  9],
       [10, 11, 12]])

In [31]:
np.r_[arr1, arr2]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
arr = np.arange(6)

In [38]:
arr1 = arr1.reshape((3, 2))
arr2 = arr2.reshape((3, 2))

In [39]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 1,  2,  0],
       [ 3,  4,  1],
       [ 5,  6,  2],
       [ 7,  8,  3],
       [ 9, 10,  4],
       [11, 12,  5]])

In [40]:
np.r_[arr1, arr2]

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [42]:
arr

array([0, 1, 2, 3, 4, 5])

In [45]:
arr.repeat([2, 3, 1, 5, 6, 0])

array([0, 0, 1, 1, 1, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4])

In [49]:
arr.repeat(2, axis = 0)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [50]:
arr3 = np.random.randn(2, 2)

In [51]:
arr3

array([[-0.35896209, -1.94180539],
       [ 0.73666   ,  0.41805709]])

In [52]:
arr3.repeat([2, 3], axis=1)

array([[-0.35896209, -0.35896209, -1.94180539, -1.94180539, -1.94180539],
       [ 0.73666   ,  0.73666   ,  0.41805709,  0.41805709,  0.41805709]])

In [53]:
np.tile(arr3, 2)

array([[-0.35896209, -1.94180539, -0.35896209, -1.94180539],
       [ 0.73666   ,  0.41805709,  0.73666   ,  0.41805709]])