In [5]:
import numpy as np

## Random Number 

In [6]:
ds=np.random.randn(3,3)

In [7]:
ds

array([[-0.41580806,  1.91742474, -1.45800475],
       [ 0.29637665, -0.29553404,  1.7814679 ],
       [-0.76148091, -1.65620538, -1.33495931]])

In [8]:
ds*ds

array([[0.17289634, 3.67651761, 2.12577785],
       [0.08783912, 0.08734037, 3.17362787],
       [0.57985318, 2.74301625, 1.78211636]])

In [9]:
ds+ds

array([[-0.83161612,  3.83484947, -2.9160095 ],
       [ 0.5927533 , -0.59106808,  3.5629358 ],
       [-1.52296182, -3.31241076, -2.66991862]])

In [11]:
ds.shape

(3, 3)

In [12]:
ds.dtype

dtype('float64')

## Creating ndarray

In [15]:
ds1=[2,4,6,7.2]
num1=np.array(ds1)

In [16]:
num1

array([2. , 4. , 6. , 7.2])

In [18]:
ds2=[[1,2,3,4],[3,4,4,5]]
num2=np.array(ds2)

In [19]:
num2

array([[1, 2, 3, 4],
       [3, 4, 4, 5]])

In [21]:
num2.shape

(2, 4)

In [22]:
num2.dtype

dtype('int32')

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.empty((4,5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.11261230e-306, 1.24608550e-306],
       [8.01070728e-307, 1.33511562e-306, 1.42418987e-306,
        1.37961641e-306, 1.60220528e-306],
       [1.24611266e-306, 9.34598925e-307, 1.24612081e-306,
        1.11260755e-306, 1.60220393e-306],
       [1.51320640e-306, 9.34609790e-307, 1.86921279e-306,
        1.24610723e-306, 1.50008929e+248]])

In [27]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])