# Indexing and Slicing:

### 1D:

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5]

5

In [4]:
arr[3:7]

array([3, 4, 5, 6])

In [5]:
arr[3:7] = 15

In [6]:
arr

array([ 0,  1,  2, 15, 15, 15, 15,  7,  8,  9])

In [7]:
a = arr[3:7]
a[1] = 1234

In [8]:
arr

array([   0,    1,    2,   15, 1234,   15,   15,    7,    8,    9])

In [9]:
a[:] = 6

In [10]:
arr

array([0, 1, 2, 6, 6, 6, 6, 7, 8, 9])

### 2D:

In [17]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr2d[2]

array([7, 8, 9])

In [20]:
arr2d[0][2]

3

In [21]:
arr2d[0,2]

3

### 3D:

In [23]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [25]:
old_values = arr3d[1].copy()
old_values

array([[ 7,  8,  9],
       [10, 11, 12]])

In [24]:
arr3d[1] = 10

In [25]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 10, 10],
        [10, 10, 10]]])

In [26]:
arr3d[1] = old_values

In [27]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
arr3d[0, 0]

array([1, 2, 3])

In [30]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [34]:
arr2d[1, :2] = 13

In [35]:
arr2d

array([[ 1,  2,  3],
       [13, 13,  6],
       [ 7,  8,  9]])