# Mathematical and Statistical functions:

In [1]:
import numpy as np

In [2]:
x = np.arange(16).reshape(4, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
x.mean()

7.5

In [5]:
np.mean(x, axis = 0)

array([6., 7., 8., 9.])

In [6]:
x.sum()

120

In [7]:
np.sum(x, axis = 1)

array([ 6, 22, 38, 54])

In [8]:
y = np.arange(5)

In [9]:
y

array([0, 1, 2, 3, 4])

In [10]:
y.cumsum()

array([ 0,  1,  3,  6, 10], dtype=int32)

In [12]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.cumsum(x, axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]], dtype=int32)

In [13]:
np.cumsum(x, axis = 1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38],
       [12, 25, 39, 54]], dtype=int32)

In [14]:
np.cumprod(x, axis = 0)

array([[   0,    1,    2,    3],
       [   0,    5,   12,   21],
       [   0,   45,  120,  231],
       [   0,  585, 1680, 3465]], dtype=int32)

In [15]:
np.cumprod(x, axis = 1)

array([[    0,     0,     0,     0],
       [    4,    20,   120,   840],
       [    8,    72,   720,  7920],
       [   12,   156,  2184, 32760]], dtype=int32)

In [16]:
y

array([0, 1, 2, 3, 4])

In [17]:
y>3

array([False, False, False, False,  True])

In [19]:
(y<3).sum()

3

In [20]:
a = np.array([3, 2, 1, 6, 4, 3])
a

array([3, 2, 1, 6, 4, 3])

In [21]:
np.sort(a)

array([1, 2, 3, 3, 4, 6])