# File input and output with arrays:

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.save('array', arr)

In [3]:
np.load('array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.savez('array2.npz', a = arr, b = arr[0:4])

In [7]:
abc = np.load('array2.npz')

In [9]:
abc['b']

array([0, 1, 2, 3])

In [10]:
x = np.arange(6)
y = np.arange(6)

In [11]:
print(x, y)

[0 1 2 3 4 5] [0 1 2 3 4 5]


In [13]:
x.dot(y)

55

In [14]:
np.dot(x, y)

55

In [16]:
one = np.ones(6)

In [18]:
print(x, one)

[0 1 2 3 4 5] [1. 1. 1. 1. 1. 1.]


In [17]:
np.dot(x, one)

15.0

In [19]:
x @ y

55

In [20]:
x * y

array([ 0,  1,  4,  9, 16, 25])

In [21]:
array = np.arange(25).reshape(5, 5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
array.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [24]:
np.transpose(array)

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])